### PR TITLE
Upgrade to chardet 3.0.2

### PR DESCRIPTION
**Pull request by dan-blanchard**
I recently pushed out the first releases in years, so it'd be good to get those on conda forge.

### CODE REVIEW

**Comment by jakirkham** [comment]
Please make sure to fork and submit PRs from your fork. Adding branches to the main feedstock will cause CIs to deploy as soon as they pass. Submitting PRs from your fork should avoid this behavior.

**Comment by dan-blanchard** [comment]
Replaced by #5.

**Comment by jakirkham** [comment]
Thanks @dan-blanchard. Would recommend bumping the build number too.

Also appears the Python 2.7 package from this release appears to be broken. Seems to be some [locking issue]( https://travis-ci.org/conda-forge/staged-recipes/builds/223141658#L173-L175 ). Guessing a fresh package will be all that is needed.

**Comment by jakirkham** [comment]
Have pulled the macOS Python 2.7 package of `chardet` this uploaded. Somehow we are unable to install that package. Not totally sure what is wrong with it. However this seems like the easiest way to fix the issue.

**Comment by jakirkham** [comment]
Appears that actually the two Travis CI builds were able to upload the same package twice. Hence the issue. Pulling one of them let the other one install.

**Pull request closed without merging**
